[project]
name = "renci-ner"
version = "1.0.1"
description = "A library for accessing RENCI NER services."
readme = "README.md"
authors = [
    { name = "Gaurav Vaidya", email = "gaurav@renci.org" }
]
keywords = ['biomedical', 'ner', 'nlp', 'named entity recognition', 'natural language processing', 'named entity linking']
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
]
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "en-core-sci-sm",
    "en-core-web-md",
    "requests>=2.32.3",
    "scispacy>=0.6.2",
    "spacy-streamlit>=1.0.6",
    "streamlit>=1.51.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.0",
]

[tool.uv.sources]
en-core-sci-sm = { url = "https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_sm-0.5.4.tar.gz" }
en-core-web-md = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl" }

[project.scripts]
renci-ner = "renci_ner.cli:renci_ner"
lemur = "lemur.app:main"
