# Publish renci-ner to PyPI (https://pypi.org/project/renci-ner/)

name: Publish to PyPI (https://pypi.org/project/renci-ner/)
on:
  pull_request:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Publish to PyPI
        run: uv publish
